[package]
name = "rust"
version = "0.0.1"
edition = "2021"

[dependencies]
once_cell = "1.20"          # Compatibility with Rust 1.61.
regex = "<1.10"				# Compatibility with Rust 1.61.
concurrent-queue = "2.5"
parking_lot = "0.12"

[[bin]]
name = "silo"
path = "src/silo.rs"
